# Run training of CLRS algorithm

Copied main function from clrs_train.py. Helper functions are located in clrs_train_funcs.py

In [143]:
import functools
import os
import shutil
from typing import Any, Dict, List

import logging
import clrs
import jax
import jax.numpy as jnp
import numpy as np
import requests
import tensorflow as tf
import haiku as hk

import model
import flags
from clrs_train_funcs import *

In [144]:
!nvidia-smi

Fri Mar 24 00:05:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.65       Driver Version: 527.56       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8    14W / 149W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [145]:
FLAGS = flags.FLAGS

In [146]:
logger = logging.getLogger()
logger.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch = logging.StreamHandler()
ch.setFormatter(formatter)
logger.addHandler(ch)

In [164]:
if FLAGS.hint_mode == 'encoded_decoded':
    encode_hints = True
    decode_hints = True
elif FLAGS.hint_mode == 'decoded_only':
    encode_hints = False
    decode_hints = True
elif FLAGS.hint_mode == 'none':
    encode_hints = False
    decode_hints = False
else:
    raise ValueError(
        'Hint mode not in {encoded_decoded, decoded_only, none}.')

train_lengths = [int(x) for x in FLAGS.train_lengths]

rng = np.random.RandomState(FLAGS.seed)
rng_key = jax.random.PRNGKey(rng.randint(2**32))

In [165]:
# Create samplers
(train_samplers,
 val_samplers, val_sample_counts,
 test_samplers, test_sample_counts,
 spec_list) = create_samplers(rng, train_lengths)

2023-03-24 00:10:44,375 - root - INFO - Creating samplers for algo binary_search
2023-03-24 00:10:44,375 - root - INFO - Creating samplers for algo binary_search
2023-03-24 00:10:44,377 - absl - WARNING - Ignoring kwargs {'p', 'length_needle'} when building sampler class <class 'clrs._src.samplers.SearchSampler'>
2023-03-24 00:10:44,377 - absl - WARNING - Ignoring kwargs {'p', 'length_needle'} when building sampler class <class 'clrs._src.samplers.SearchSampler'>
2023-03-24 00:10:44,378 - absl - WARNING - Sampling dataset on-the-fly, unlimited samples.
2023-03-24 00:10:44,378 - absl - WARNING - Sampling dataset on-the-fly, unlimited samples.
2023-03-24 00:10:44,546 - absl - WARNING - Ignoring kwargs {'p', 'length_needle'} when building sampler class <class 'clrs._src.samplers.SearchSampler'>
2023-03-24 00:10:44,546 - absl - WARNING - Ignoring kwargs {'p', 'length_needle'} when building sampler class <class 'clrs._src.samplers.SearchSampler'>
2023-03-24 00:10:44,548 - absl - WARNING - S

In [166]:
FLAGS.l1_weight = 0.01 # 0.001 
FLAGS.hidden_size = 128 # 32
FLAGS.msg_size = 32 # 32

FLAGS.train_steps = 10000 # 1000
FLAGS.eval_every = 50
FLAGS.test_every = 500

l1_weight_fn_mult_start = 1
l1_weight_fn_mult_end = 10

l1_weight_fn = lambda step: FLAGS.l1_weight * (l1_weight_fn_mult_start + step / FLAGS.train_steps * (l1_weight_fn_mult_end - l1_weight_fn_mult_start))

In [167]:
# FLAGS.hidden_size = 8
# FLAGS.algorithms = ['dijkstra']

In [169]:
processor_factory = model.get_processor_factory(
    FLAGS.processor_type,
    use_ln=FLAGS.use_ln,
    nb_triplet_fts=FLAGS.nb_triplet_fts,
    nb_heads=FLAGS.nb_heads
)
model_params = dict(
    processor_factory=processor_factory,
    hidden_dim=FLAGS.hidden_size,
    msg_dim=FLAGS.msg_size,
    encode_hints=encode_hints,
    decode_hints=decode_hints,
    encoder_init=FLAGS.encoder_init,
    use_lstm=FLAGS.use_lstm,
    learning_rate=FLAGS.learning_rate,
    grad_clip_max_norm=FLAGS.grad_clip_max_norm,
    checkpoint_path=FLAGS.checkpoint_path,
    freeze_processor=FLAGS.freeze_processor,
    dropout_prob=FLAGS.dropout_prob,
    hint_teacher_forcing=FLAGS.hint_teacher_forcing,
    hint_repred_mode=FLAGS.hint_repred_mode,
    nb_msg_passing_steps=FLAGS.nb_msg_passing_steps,
    l1_weight=FLAGS.l1_weight
)

eval_model = model.BaselineMsgModel(
    spec=spec_list,
    dummy_trajectory=[next(t) for t in val_samplers],
    **model_params
)
# # we will never used chunked training
# if FLAGS.chunked_training:
#     train_model = clrs.models.BaselineModelChunked(
#         spec=spec_list,
#         dummy_trajectory=[next(t) for t in train_samplers],
#         **model_params
#     )
# else:
#     train_model = eval_model
train_model = eval_model

In [170]:
# Training loop.
best_score = -1.0
current_train_items = [0] * len(FLAGS.algorithms)
step = 0
next_eval = 0
# Make sure scores improve on first step, but not overcome best score
# until all algos have had at least one evaluation.
val_scores = [-99999.9] * len(FLAGS.algorithms)
length_idx = 0

while step < FLAGS.train_steps:
    feedback_list = [next(t) for t in train_samplers]

    # Initialize model.
    if step == 0:
        all_features = [f.features for f in feedback_list]
        if FLAGS.chunked_training:
            # We need to initialize the model with samples of all lengths for
            # all algorithms. Also, we need to make sure that the order of these
            # sample sizes is the same as the order of the actual training sizes.
            all_length_features = [all_features] + [
                [next(t).features for t in train_samplers]
                for _ in range(len(train_lengths))]
            train_model.init(all_length_features[:-1], FLAGS.seed + 1)
        else:
            train_model.init(all_features, FLAGS.seed + 1)

    train_model.l1_weight = l1_weight_fn(step)
    # Training step.
    for algo_idx in range(len(train_samplers)):
        feedback = feedback_list[algo_idx]
        rng_key, new_rng_key = jax.random.split(rng_key)
        if FLAGS.chunked_training:
            # In chunked training, we must indicate which training length we are
            # using, so the model uses the correct state.
            length_and_algo_idx = (length_idx, algo_idx)
        else:
            # In non-chunked training, all training lengths can be treated equally,
            # since there is no state to maintain between batches.
            length_and_algo_idx = algo_idx
        cur_loss = train_model.feedback(
            rng_key, feedback, length_and_algo_idx)
        rng_key = new_rng_key

        if FLAGS.chunked_training:
            examples_in_chunk = np.sum(feedback.features.is_last).item()
        else:
            examples_in_chunk = len(feedback.features.lengths)
        current_train_items[algo_idx] += examples_in_chunk
        if step % 50 == 0:
            logging.info('Algo %s step %i current loss %f, current_train_items %i, l1_weight %f.',
                        FLAGS.algorithms[algo_idx], step,
                        cur_loss, current_train_items[algo_idx], train_model.l1_weight)

    # Periodically evaluate model
    if step >= next_eval:
        eval_model.params = train_model.params
        for algo_idx in range(len(train_samplers)):
            common_extras = {'examples_seen': current_train_items[algo_idx],
                             'step': step,
                             'algorithm': FLAGS.algorithms[algo_idx]}

            # Validation info.
            new_rng_key, rng_key = jax.random.split(rng_key)
            val_stats = collect_and_eval(
                val_samplers[algo_idx],
                functools.partial(eval_model.predict,
                                  algorithm_index=algo_idx),
                val_sample_counts[algo_idx],
                new_rng_key,
                extras=common_extras)
            logging.info('(val) algo %s step %d: %s',
                         FLAGS.algorithms[algo_idx], step, val_stats)
            val_scores[algo_idx] = val_stats['score']

        next_eval += FLAGS.eval_every

        # If best total score, update best checkpoint.
        # Also save a best checkpoint on the first step.
        msg = (f'best avg val score was '
               f'{best_score/len(FLAGS.algorithms):.3f}, '
               f'current avg val score is {np.mean(val_scores):.3f}, '
               f'val scores are: ')
        msg += ', '.join(
            ['%s: %.3f' % (x, y) for (x, y) in zip(FLAGS.algorithms, val_scores)])
        if (sum(val_scores) > best_score) or step == 0:
            best_score = sum(val_scores)
            logging.info('Checkpointing best model, %s', msg)
            train_model.save_model('best.pkl')
        else:
            logging.info('Not saving new best model, %s', msg)

    step += 1
    length_idx = (length_idx + 1) % len(train_lengths)

logging.info('Checkpointing final model, %s', msg)
train_model.save_model('final.pkl')

# logging.info('Restoring best model from checkpoint...')
# eval_model.restore_model('best.pkl', only_load_processor=False)
logging.info('Restoring final model from checkpoint...')
eval_model.restore_model('final.pkl', only_load_processor=False)

2023-03-24 00:11:48,106 - root - INFO - Algo binary_search step 0 current loss 7.931198, current_train_items 32, l1_weight 0.010000.
2023-03-24 00:11:48,106 - root - INFO - Algo binary_search step 0 current loss 7.931198, current_train_items 32, l1_weight 0.010000.
2023-03-24 00:11:49,732 - root - INFO - (val) algo binary_search step 0: {'return': 0.0556640625, 'score': 0.0556640625, 'examples_seen': 32, 'step': 0, 'algorithm': 'binary_search'}
2023-03-24 00:11:49,732 - root - INFO - (val) algo binary_search step 0: {'return': 0.0556640625, 'score': 0.0556640625, 'examples_seen': 32, 'step': 0, 'algorithm': 'binary_search'}
2023-03-24 00:11:49,734 - root - INFO - Checkpointing best model, best avg val score was -1.000, current avg val score is 0.056, val scores are: binary_search: 0.056
2023-03-24 00:11:49,734 - root - INFO - Checkpointing best model, best avg val score was -1.000, current avg val score is 0.056, val scores are: binary_search: 0.056
2023-03-24 00:12:19,922 - root - INF

In [171]:
import pickle

def restore_model(model, file_name):
    """Restore model from `file_name`."""
    with open(file_name, 'rb') as f:
        restored_state = pickle.load(f)
        restored_params = restored_state['params']
        model.params = hk.data_structures.merge(restored_params)
        model.opt_state = restored_state['opt_state']

def save_model(model, file_name):
    """Save model (processor weights only) to `file_name`."""
    to_save = {'params': model.params, 'opt_state': model.opt_state}
    with open(file_name, 'wb') as f:
        pickle.dump(to_save, f)

In [172]:
# save_model(eval_model, 'eval_model_1e-3.pkl')

In [173]:
# restore_model(eval_model, 'eval_model_asdf.pkl')

In [174]:
algo_idx = 0
common_extras = {}

new_rng_key, rng_key = jax.random.split(rng_key)
val_stats = collect_and_eval(
    val_samplers[algo_idx],
    functools.partial(eval_model.predict, algorithm_index=algo_idx),
    val_sample_counts[algo_idx],
    new_rng_key,
    extras=common_extras)

print(val_stats)

{'return': 0.90673828125, 'score': 0.90673828125}


In [175]:
new_rng_key, rng_key = jax.random.split(rng_key)
test_stats = collect_and_eval(
    test_samplers[algo_idx],
    functools.partial(eval_model.predict, algorithm_index=algo_idx),
    test_sample_counts[algo_idx],
    new_rng_key,
    extras=common_extras)

print(test_stats)

{'return': 0.46044921875, 'score': 0.46044921875}


In [176]:
feedback = next(train_samplers[0])

In [177]:
list(filter(lambda x: x[:2] != '__', dir(feedback)))

['_asdict',
 '_field_defaults',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'count',
 'features',
 'index',
 'outputs']

In [178]:
list(filter(lambda x: x[:2] != '__', dir(feedback.features)))

['_asdict',
 '_field_defaults',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'count',
 'hints',
 'index',
 'inputs',
 'lengths']

In [179]:
feedback.features

Features(inputs=(DataPoint(name="pos",	location=node,	type=scalar,	data=Array(32, 4)), DataPoint(name="key",	location=node,	type=scalar,	data=Array(32, 4)), DataPoint(name="target",	location=graph,	type=scalar,	data=Array(32,)), DataPoint(name="pred",	location=node,	type=pointer,	data=Array(32, 4))), hints=(DataPoint(name="low",	location=node,	type=mask_one,	data=Array(3, 32, 4)), DataPoint(name="high",	location=node,	type=mask_one,	data=Array(3, 32, 4)), DataPoint(name="mid",	location=node,	type=mask_one,	data=Array(3, 32, 4))), lengths=array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]))

In [180]:
feedback.features.inputs

(DataPoint(name="pos",	location=node,	type=scalar,	data=Array(32, 4)),
 DataPoint(name="key",	location=node,	type=scalar,	data=Array(32, 4)),
 DataPoint(name="target",	location=graph,	type=scalar,	data=Array(32,)),
 DataPoint(name="pred",	location=node,	type=pointer,	data=Array(32, 4)))

In [181]:
feedback.features.inputs[0].data

array([[0.14321858, 0.42976862, 0.67552152, 0.82510737],
       [0.24357671, 0.63700019, 0.80225663, 0.91029176],
       [0.02518637, 0.13488037, 0.72233318, 0.74433278],
       [0.02659357, 0.138963  , 0.81119306, 0.86907649],
       [0.2592989 , 0.45766249, 0.70142918, 0.74301219],
       [0.40183101, 0.60396602, 0.61165408, 0.68710441],
       [0.13113083, 0.28998422, 0.30829217, 0.7026927 ],
       [0.45379258, 0.45453447, 0.48747734, 0.62159454],
       [0.13758911, 0.17218193, 0.39262778, 0.52913867],
       [0.24213853, 0.26835611, 0.32407588, 0.87429476],
       [0.68216987, 0.691791  , 0.96690824, 0.98998814],
       [0.11567689, 0.55187071, 0.79336439, 0.8410712 ],
       [0.11566215, 0.29025702, 0.39962879, 0.62896886],
       [0.07141768, 0.54445591, 0.65805865, 0.69995374],
       [0.21459105, 0.31837276, 0.47813607, 0.67011221],
       [0.28179068, 0.29279508, 0.5834445 , 0.86139307],
       [0.51513414, 0.79130254, 0.8468094 , 0.98322896],
       [0.09444165, 0.11045878,

In [182]:
feedback.features.inputs[1].data

array([[0.14505245, 0.50669634, 0.69746885, 0.99827601],
       [0.04907691, 0.55939811, 0.60407716, 0.69362913],
       [0.22850282, 0.32995465, 0.45680348, 0.4631161 ],
       [0.60183918, 0.61901712, 0.75530681, 0.84752412],
       [0.06522265, 0.49855728, 0.71561711, 0.74078881],
       [0.13983012, 0.26721134, 0.34307139, 0.61253297],
       [0.44517601, 0.59939087, 0.70310817, 0.71624527],
       [0.21499737, 0.22490709, 0.2290317 , 0.27179855],
       [0.0659541 , 0.36794665, 0.64325931, 0.66634537],
       [0.00141337, 0.02005159, 0.42050811, 0.75774222],
       [0.47937064, 0.76829195, 0.77577855, 0.89999182],
       [0.11322815, 0.4436976 , 0.45798428, 0.73927385],
       [0.02718076, 0.39560593, 0.47574331, 0.57584161],
       [0.25199846, 0.42218847, 0.66165925, 0.75193187],
       [0.17945598, 0.19686362, 0.23018133, 0.98835444],
       [0.03165351, 0.19228618, 0.82584994, 0.9468503 ],
       [0.17438562, 0.74685971, 0.74929382, 0.85605148],
       [0.10119071, 0.32314454,

In [183]:
feedback.features.inputs[2].data

array([0.90789178, 0.76675769, 0.46466379, 0.21048436, 0.19953704,
       0.71214855, 0.72076151, 0.11210543, 0.72746734, 0.47947478,
       0.50966803, 0.45263618, 0.77380012, 0.48942764, 0.96081892,
       0.95727694, 0.10890818, 0.5357713 , 0.80139012, 0.57620145,
       0.93474738, 0.89697058, 0.57118694, 0.48263026, 0.2236446 ,
       0.6904246 , 0.91944913, 0.11814233, 0.64556645, 0.37133494,
       0.4398061 , 0.70607906])

In [184]:
feedback.features.inputs[3].data

array([[0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.],
       [0., 0., 1., 2.]])

In [185]:
A = feedback.features.inputs[2].data
adj = feedback.features.inputs[3].data

In [186]:
jnp.where(jnp.expand_dims((A != 0), 1) & (adj == 0))

(Array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
         8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 16, 16,
        17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25,
        25, 26, 26, 27, 27, 28, 28, 29, 29, 30, 30, 31, 31], dtype=int32),
 Array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],      dtype=int32))

In [187]:
feedback.features.hints

(DataPoint(name="low",	location=node,	type=mask_one,	data=Array(3, 32, 4)),
 DataPoint(name="high",	location=node,	type=mask_one,	data=Array(3, 32, 4)),
 DataPoint(name="mid",	location=node,	type=mask_one,	data=Array(3, 32, 4)))

In [188]:
np.argmin(feedback.features.inputs[0].data, axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [189]:
np.where(feedback.outputs[0].data == 1)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]),
 array([3, 3, 3, 0, 1, 3, 3, 0, 3, 3, 1, 2, 3, 2, 3, 3, 0, 3, 3, 1, 3, 3,
        1, 3, 1, 2, 3, 0, 2, 3, 3, 3]))

In [190]:
test_sample_counts[0]

2048

In [191]:
feedback.features

Features(inputs=(DataPoint(name="pos",	location=node,	type=scalar,	data=Array(32, 4)), DataPoint(name="key",	location=node,	type=scalar,	data=Array(32, 4)), DataPoint(name="target",	location=graph,	type=scalar,	data=Array(32,)), DataPoint(name="pred",	location=node,	type=pointer,	data=Array(32, 4))), hints=(DataPoint(name="low",	location=node,	type=mask_one,	data=Array(3, 32, 4)), DataPoint(name="high",	location=node,	type=mask_one,	data=Array(3, 32, 4)), DataPoint(name="mid",	location=node,	type=mask_one,	data=Array(3, 32, 4))), lengths=array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]))

In [192]:
def _concat(dps, axis):
    return jax.tree_util.tree_map(lambda *x: np.concatenate(x, axis), *dps)

def get_msgs(sampler, predict_fn, sample_count, rng_key, sample_prob=0.001, threshold_max_elem=0.001):
    """Get messages from model.
    
    CAUTION: size of msgs can get large very quickly, so beware when
        running with a large number of samples.
    Use sample_prob to reduce the number of messages that are saved
    by randomly sampling messages
    
    Note: we can only perform symbolic regression on a maximum of
    ~5000 messages anyways, so we can use sample_prob to get to this threshold
    """
    processed_samples = 0
    msgs = []
    while processed_samples < sample_count:
        feedback = next(sampler)
        batch_size = feedback.outputs[0].data.shape[0]
        new_rng_key, rng_key = jax.random.split(rng_key)
        _, _, cur_msgs, cur_input_msg, cur_input_algo = predict_fn(new_rng_key, feedback.features)
        
        print(cur_msgs.shape, cur_msgs.shape[-1], cur_input_msg.shape[-1], cur_input_algo.shape[-1])
        
        cur_msgs = cur_msgs.reshape(-1, cur_msgs.shape[-1])
        cur_input_msg = cur_input_msg.reshape(-1, cur_input_msg.shape[-1])
        cur_input_algo = cur_input_algo.reshape(-1, cur_input_algo.shape[-1])
        cur_msg_concat = jnp.concatenate((cur_msgs, cur_input_msg, cur_input_algo), axis=-1)
        
        max_element_mask = jnp.max(jnp.abs(cur_msgs), axis=1) > threshold_max_elem
        print(jnp.sum(max_element_mask), "of", cur_msg_concat.shape[0])
        cur_msg_concat = cur_msg_concat[max_element_mask]

        sampled_rate = jnp.sum(max_element_mask) / cur_msg_concat.shape[0]
        new_sample_prob = max(1., sample_prob / sampled_rate)
        print("New sample prob:", new_sample_prob)

        new_rng_key, rng_key = jax.random.split(rng_key)
        mask = jax.random.choice(new_rng_key,
                                 a=jnp.array([False, True]),
                                 shape=(cur_msg_concat.shape[0],),
                                 p=jnp.array([1 - new_sample_prob, new_sample_prob]),
                                 replace=True,)
        cur_msg_concat = cur_msg_concat[mask]
        
        msgs.append(cur_msg_concat)
        processed_samples += batch_size
    msgs = _concat(msgs, axis=0)
    
    return msgs


In [193]:
new_rng_key, rng_key = jax.random.split(rng_key)
batched_msgs = get_msgs(
    test_samplers[0],
    functools.partial(eval_model.predict, algorithm_index=0),
#     test_sample_counts[0],  # EXPLODING MEMORY LOL
    32*4,
    new_rng_key,
    0.01)

batched_msgs.shape

(32, 6, 64, 64, 32) 32 512 13
28523 of 786432
New sample prob: 1.0
(32, 6, 64, 64, 32) 32 512 13
30172 of 786432
New sample prob: 1.0
(32, 6, 64, 64, 32) 32 512 13
26350 of 786432
New sample prob: 1.0
(32, 6, 64, 64, 32) 32 512 13
29093 of 786432
New sample prob: 1.0


(114138, 557)

In [194]:
jnp.sum(jnp.linalg.norm(batched_msgs[:,:32],axis=1) < 0.01)

Array(7388, dtype=int32)

In [195]:
jnp.sum(jnp.max(jnp.abs(batched_msgs[:,:32]),axis=1) < 0.001)

Array(0, dtype=int32)

In [196]:
batched_msgs[0][:32], batched_msgs[1][:32], batched_msgs[2][:32]

(array([ 1.1450899e-03,  3.0493271e-01, -7.0226123e-03,  5.5017211e-03,
        -3.3310526e-03, -3.4543457e-03, -3.9997096e-03,  2.4176376e-02,
        -3.9362758e-02,  5.2284030e-03,  1.8895140e-02, -1.2220181e-02,
         1.1158266e+00,  9.2786178e-03, -1.4858229e-02,  2.9484518e-02,
         3.0890487e-03,  1.2021033e-03,  1.9113364e-02,  4.7650129e-02,
         6.2272572e-03, -3.3184785e-02, -2.1826087e-02,  9.7039798e-03,
         1.1541070e-02,  1.2142320e-02, -8.9339195e-03, -2.7423752e-03,
         2.1350238e-04,  3.0472608e-02,  1.5531649e-02, -4.6320334e-03],
       dtype=float32),
 array([ 3.0902242e-03,  3.5536268e-01, -8.5462863e-03,  6.2940679e-03,
        -2.1298146e-03, -1.9835152e-03, -4.9694045e-03,  2.3561740e-02,
        -4.0676109e-02,  6.3245124e-03,  2.1046914e-02, -1.2772582e-02,
         1.2850626e+00,  7.1481206e-03, -1.5043028e-02,  2.7941227e-02,
         4.1221813e-03,  1.1775742e-03,  1.8791756e-02,  4.2827357e-02,
         7.2685848e-03, -3.8506620e-02, 

In [197]:
file_name = 'binary_search_val_msgs.pkl'
with open(file_name, 'wb') as f:
    pickle.dump(batched_msgs, f)

In [198]:
import sys
sys.getsizeof(batched_msgs)

254299592

In [199]:
test_sample_counts[0]

2048

In [200]:
sys.getsizeof(batched_msgs) / 1000000

254.299592